#!/bin/bash

######################
# USER CONFIGURATION #
######################

AMPATH=/usr/sbin

##########################
# END USER CONFIGURATION #
##########################

$AMPATH/amdump $1
$AMPATH/amcheckdump $1
