#!/bin/bash

######################
# USER CONFIGURATION #
######################

AMPATH=/usr/sbin

##########################
# END USER CONFIGURATION #
##########################

$AMPATH/amdump $1

if [ "$?" != "0" ]; then
  echo "amdump failed.  Aborting."
  exit
fi

$AMPATH/amcheckdump $1
