#!/bin/bash

######################
# USER CONFIGURATION #
######################

DEV_LABEL_PATH=/dev/disk/by-label
SLOTS_PATH=/var/archive/vtapes/daily/slots
TAPE_LIST=/var/lib/amanda/bin/custom/mount.tapes
USER=amandabackup
GROUP=disk

##########################
# END USER CONFIGURATION #
##########################

do_mount_by_label () {
  if [ -e "$DEV_LABEL_PATH/$1" ]; then
    existing_mount=$(mount|grep "$SLOTS_PATH/$2")
    if [ "$existing_mount" != "" ]; then
      echo "Active mount detected: $existing_mount"
      echo "Continuing..."
      return
    fi
    sudo mount -t ext3 $DEV_LABEL_PATH/$1 $SLOTS_PATH/$2
    if [ "$?" != "0" ]; then
      echo "Failed while attempting to mount $DEV_LABEL_PATH/$1 to $SLOTS_PATH/$2"
      exit 1
    fi
    sudo chown $USER.$GROUP $SLOTS_PATH/$2
    if [ "$?" != "0" ]; then
      echo "Failed while attempting to chown $USER.$GROUP $SLOTS_PATH/$2"
      exit 2
    fi
    echo "SUCCESS: Mounted $DEV_LABEL_PATH/$1 to $SLOTS_PATH/$2"
  fi
}

source $TAPE_LIST
